version: '3.8'

services:
  web:
    build: .
    container_name: my_php_app
    ports:
      - "8080:80"
    volumes:
      - ./App:/var/www/html/App
      - ./assets:/var/www/html/assets
      - ./index.html:/var/www/html/index.html
      - ./main.js:/var/www/html/main.js
      - ./vendors:/var/www/html/vendors
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - PHP_ENV=development